'use strict';
/**
 * board-observability.test.cjs — the six observability sources the board grew on
 * 2026-08-23 (bots Hermes, colas, acciones firmadas, rollup, waker, census).
 *
 * What must never regress:
 *  - PER-SOURCE FAIL-SOFT. One unreadable source must not blank the other five,
 *    and every source must declare its own generated_at. That property is the
 *    entire reason this block is six objects instead of one.
 *  - The wake-class back-fill stays in step with the real classifier: the reason
 *    strings in these tests are GENERATED by orchestrator-turn's classifyWake,
 *    never typed by hand, so a wording change there fails here instead of
 *    silently emptying the histogram.
 *  - A queue record is undelivered unless it says ok:true.
 *  - The census never blocks a request (async cache, injected runner — this
 *    suite must never shell out to the real schtasks).
 *
 * All IO goes to temp dirs. Nothing here may touch the real _intel.
 */
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const {
  buildObservability,
  classOfReason, classesOfTurn, summarizeWakerTurns,
  summarizeQueueRecords, rollupStatus,
  readBriefs, readQueues, readActions, readRollup, readWaker,
  makeCensusCache,
} = require('../board-app/lib/observability.cjs');
const { classifyWake } = require('../scripts/orchestrator-turn.cjs');

function tmpIntel(name) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), `obs-${name}-`));
  return dir;
}
const write = (file, text) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
};
const jsonl = (rows) => rows.map((r) => JSON.stringify(r)).join('\n') + '\n';

// ── wake classes ────────────────────────────────────────────────────────────

/**
 * The anti-drift test. classifyWake owns the reason wording; this asserts the
 * board's inverse mapping agrees with it for every class the classifier can
 * emit. If someone rewords a reason in orchestrator-turn.cjs, this fails —
 * which is the point, because the alternative is a histogram that quietly
 * reclassifies everything as `noise`.
 */
test('classOfReason: agrees with classifyWake for every class it emits', () => {
  const cases = [
    { input: { gateExit: 1, reviewCount: 0 }, expect: ['real-stall'] },
    { input: { gateExit: 3, reviewCount: 0 }, expect: ['exception'] },
    { input: { gateExit: 7, reviewCount: 0 }, expect: ['exception'] },
    { input: { gateExit: 0, reviewCount: 2 }, expect: ['results-directed'] },
    {
      input: { gateExit: 0, reviewCount: 0, events: [{ event: 'result-file', repo: 'wezbridge' }] },
      expect: ['results-directed'],
    },
    {
      input: { gateExit: 0, reviewCount: 0, events: [{ event: 'permission-wait', repo: 'infra', bypass: false }] },
      expect: ['exception'],
    },
    { input: { gateExit: 1, reviewCount: 3 }, expect: ['real-stall', 'results-directed'] },
  ];
  for (const c of cases) {
    const { reasons, classes } = classifyWake(c.input);
    assert.deepStrictEqual(classes, c.expect, `classifyWake changed shape for ${JSON.stringify(c.input)}`);
    assert.deepStrictEqual(
      reasons.map(classOfReason), c.expect,
      `board mapping drifted from classifyWake wording: ${JSON.stringify(reasons)}`,
    );
  }
});

test('classesOfTurn: the written field wins; reasons back-fill the old records', () => {
  // New-shape record: trust what the classifier wrote, even if the reason text
  // would map elsewhere.
  assert.deepStrictEqual(
    classesOfTurn({ classes: ['exception'], reasons: ['gate RED: work past deadline with no ruling'] }),
    ['exception'],
  );
  // Old-shape record (the 91 turns already on disk): derive.
  assert.deepStrictEqual(
    classesOfTurn({ reasons: ['gate RED: work past deadline with no ruling'] }),
    ['real-stall'],
  );
  assert.deepStrictEqual(classesOfTurn({}), []);
  assert.deepStrictEqual(classesOfTurn(null), []);
});

test('summarizeWakerTurns: woke vs skipped counted apart, histogram over all four classes', () => {
  const turns = [
    { at: '2026-08-22T10:00:00.000Z', woke: false, action: 'none', reasons: [] },
    { at: '2026-08-22T12:00:00.000Z', woke: true, action: 'headless', reasons: ['gate RED: work past deadline with no ruling'] },
    { at: '2026-08-22T14:00:00.000Z', woke: true, action: 'poked-pane', classes: ['results-directed'] },
  ];
  const now = Date.parse('2026-08-22T15:00:00.000Z');
  const s = summarizeWakerTurns(turns, now);
  assert.strictEqual(s.total, 3);
  assert.strictEqual(s.woke, 2);
  assert.strictEqual(s.skipped, 1, 'a $0 skip is the classifier working, not a lost turn');
  assert.deepStrictEqual(s.classes, {
    'results-directed': 1, 'real-stall': 1, exception: 0, noise: 0,
  });
  assert.strictEqual(s.actions.none, 1);
  assert.strictEqual(s.last_turn_at, '2026-08-22T14:00:00.000Z');
  assert.strictEqual(s.last_turn_age_minutes, 60);
});

test('summarizeWakerTurns: no turns at all is an empty state, not a crash', () => {
  const s = summarizeWakerTurns([], Date.now());
  assert.strictEqual(s.total, 0);
  assert.strictEqual(s.last_turn_at, null);
  assert.strictEqual(s.last_turn_age_minutes, null);
  assert.deepStrictEqual(Object.values(s.classes), [0, 0, 0, 0]);
});

// ── colas ───────────────────────────────────────────────────────────────────

test('summarizeQueueRecords: only ok:true counts as delivered', () => {
  const now = Date.parse('2026-08-22T18:00:00.000Z');
  const s = summarizeQueueRecords([
    { time: '2026-08-22T17:00:00.000Z', ok: true, delivered: '2026-08-22T17:01:00.000Z' },
    // The 2026-08-22 live shape: an actions.jsonl queue_deliver exists, but the
    // durable record still says it never landed. The durable record wins.
    { time: '2026-08-22T16:00:00.000Z', ok: false, delivered: null },
    { time: '2026-08-22T15:00:00.000Z', ok: false, delivered: '2026-08-22T15:30:00.000Z' },
  ], now);
  assert.strictEqual(s.total, 3);
  assert.strictEqual(s.delivered, 1);
  assert.strictEqual(s.undelivered, 2);
  assert.strictEqual(s.oldest_undelivered_at, '2026-08-22T15:00:00.000Z');
  assert.strictEqual(s.oldest_undelivered_minutes, 180);
});

test('summarizeQueueRecords: a drained queue reports no oldest age', () => {
  const s = summarizeQueueRecords([{ time: '2026-08-22T17:00:00.000Z', ok: true }], Date.now());
  assert.strictEqual(s.undelivered, 0);
  assert.strictEqual(s.oldest_undelivered_at, null);
  assert.strictEqual(s.oldest_undelivered_minutes, null);
});

test('readQueues: per project, sorted worst-first, with waker flag counts', () => {
  const intel = tmpIntel('queues');
  write(path.join(intel, 'queues', 'wezbridge.jsonl'), jsonl([
    { id: 'a', time: '2026-08-22T17:00:00.000Z', ok: true },
  ]));
  write(path.join(intel, 'queues', 'infra.jsonl'), jsonl([
    { id: 'b', time: '2026-08-22T16:00:00.000Z', ok: false },
    { id: 'c', time: '2026-08-22T16:30:00.000Z', ok: false },
  ]));
  write(path.join(intel, '.orch-waker-state', 'flags.json'), JSON.stringify({ infra: 1 }));
  write(path.join(intel, '.orch-waker-state', 'pending.json'), JSON.stringify({}));

  const out = readQueues(intel, Date.parse('2026-08-22T18:00:00.000Z'));
  assert.ok(out.generated_at, 'every source declares its own generated_at');
  assert.strictEqual(out.projects[0].project, 'infra', 'worst queue sorts first');
  assert.strictEqual(out.projects[0].undelivered, 2);
  assert.strictEqual(out.projects[1].undelivered, 0);
  assert.strictEqual(out.total_undelivered, 2);
  assert.strictEqual(out.flags, 1);
  assert.strictEqual(out.pending, 0);
});

test('readQueues: no queues directory is an empty panel, not an error', () => {
  const out = readQueues(tmpIntel('noqueues'), Date.now());
  assert.deepStrictEqual(out.projects, []);
  assert.strictEqual(out.total_undelivered, 0);
  assert.strictEqual(out.error, undefined);
});

// ── acciones firmadas ───────────────────────────────────────────────────────

test('readActions: newest first, extra flattened, fields passed through verbatim', () => {
  const intel = tmpIntel('actions');
  write(path.join(intel, 'actions.jsonl'), jsonl([
    { ts: '2026-08-22T10:00:00.000Z', actor: 'daemon-sentinel', action: 'sentinel_poke', target: 'pane-3', why: 'heartbeat detenido 13s' },
    {
      ts: '2026-08-22T11:00:00.000Z', actor: 'queue-drain', action: 'queue_deliver', target: 'pane-14',
      why: 'corr=hermes', extra: { project: 'infra', attempts: 3 },
    },
  ]));
  const out = readActions(intel, Date.now());
  assert.strictEqual(out.count, 2);
  assert.strictEqual(out.items[0].actor, 'queue-drain', 'reverse-chron: newest action on top');
  assert.strictEqual(out.items[0].extra, 'project=infra · attempts=3');
  assert.strictEqual(out.items[1].why, 'heartbeat detenido 13s');
  assert.strictEqual(out.items[1].extra, '');
});

test('readActions: a missing log is an empty feed carrying its error', () => {
  const out = readActions(tmpIntel('noactions'), Date.now());
  assert.ok(out.error, 'the panel must say it could not read, not render silence');
  assert.ok(out.generated_at);
});

// ── rollup ──────────────────────────────────────────────────────────────────

test('rollupStatus: the 02:30 run closes YESTERDAY, in local time', () => {
  // 02:30 local on the 23rd: the job running now is writing the 22nd.
  const at0230 = new Date(2026, 7, 23, 2, 30, 0);
  const s = rollupStatus(['2026-08-22.md'], at0230);
  assert.strictEqual(s.expected, '2026-08-22');
  assert.strictEqual(s.today_local, '2026-08-23');
  assert.strictEqual(s.ran, true, "yesterday's file IS today's 02:30 deliverable");
});

test('rollupStatus: after 06:00 the current local day is what is expected', () => {
  const atNoon = new Date(2026, 7, 23, 12, 0, 0);
  assert.strictEqual(rollupStatus(['2026-08-22.md'], atNoon).ran, false, 'todavía no corrió');
  assert.strictEqual(rollupStatus(['2026-08-22.md', '2026-08-23.md'], atNoon).ran, true);
});

test('rollupStatus: only YYYY-MM-DD.md files count, newest wins', () => {
  const s = rollupStatus(['README.md', 'notas.txt', '2026-08-21.md', '2026-08-22.md'], new Date(2026, 7, 22, 12, 0, 0));
  assert.strictEqual(s.newest, '2026-08-22.md');
});

test('readRollup: renders the newest file and reports the next local run time', () => {
  const intel = tmpIntel('rollup');
  write(path.join(intel, 'rollups', '2026-08-22.md'), '# Rollup diario\n- gate GREEN\n');
  const out = readRollup(intel, new Date(2026, 7, 22, 12, 0, 0).getTime());
  assert.match(out.text, /Rollup diario/);
  assert.strictEqual(out.newest, '2026-08-22.md');
  assert.strictEqual(out.next_run_local, '02:30');
  assert.ok(out.file_at, 'the file mtime is shown so a stale rollup cannot look fresh');
});

test('readRollup: no rollups yet says so instead of rendering nothing', () => {
  const out = readRollup(tmpIntel('norollup'), Date.now());
  assert.strictEqual(out.newest, null);
  assert.strictEqual(out.text, null);
  assert.strictEqual(out.ran, false);
  assert.ok(out.expected, 'the panel can still say WHICH day is missing');
});

// ── briefs ──────────────────────────────────────────────────────────────────

test('readBriefs: an absent sensor brief is good news, not an error', () => {
  const intel = tmpIntel('briefs');
  write(path.join(intel, 'briefs', 'centinela-mas-reciente.md'), '# CENTINELA\n- COLAS ATASCADAS\n');
  const out = readBriefs(intel, Date.now());
  const [centinela, sensor] = out.items;
  assert.match(centinela.text, /CENTINELA/);
  assert.ok(centinela.last_run_at, 'mtime is the "última corrida" the operator reads');
  assert.strictEqual(sensor.missing, true);
  assert.strictEqual(sensor.text, null);
  assert.strictEqual(out.error, undefined, 'a missing alert file must not paint the panel red');
});

// ── waker ───────────────────────────────────────────────────────────────────

test('readWaker: reads the turn tail off disk and classifies old-shape records', () => {
  const intel = tmpIntel('waker');
  write(path.join(intel, 'turns', 'turn-2026-08-22T00-05-38-510Z.json'), JSON.stringify({
    at: '2026-08-22T00:00:05.889Z', woke: true, action: 'headless',
    reasons: ['gate RED: work past deadline with no ruling'],
  }));
  write(path.join(intel, 'turns', 'turn-2026-08-21T22-07-54-598Z.json'), JSON.stringify({
    at: '2026-08-21T22:00:00.000Z', woke: false, action: 'none',
    reasons: [],
  }));
  const out = readWaker(intel, Date.parse('2026-08-22T01:00:00.000Z'));
  assert.strictEqual(out.total, 2);
  assert.strictEqual(out.woke, 1);
  assert.strictEqual(out.skipped, 1);
  assert.strictEqual(out.classes['real-stall'], 1);
  assert.strictEqual(out.last_turn_age_minutes, 60);
});

test('readWaker: no turns directory is an empty state carrying generated_at', () => {
  const out = readWaker(tmpIntel('nowaker'), Date.now());
  assert.strictEqual(out.total, 0);
  assert.ok(out.generated_at);
});

// ── census (async, cached, injected runner) ─────────────────────────────────

const CSV = [
  '"HostName","TaskName","Next Run Time","Status","Last Run Time","Last Result","Scheduled Task State"',
  '"PC","\\wezbridge-fleet-board","23-Aug-26 1:00:00 AM","Ready","23-Aug-26 12:00:00 AM","0","Enabled"',
  '"PC","\\routine-test-strength-wezbridge","23-Aug-26 9:00:00 AM","Ready","22-Aug-26 9:00:00 AM","1","Enabled"',
  '"PC","\\wezbridge-steward-gate","23-Aug-26 9:05:00 AM","Ready","22-Aug-26 9:05:00 AM","1","Enabled"',
].join('\r\n');

test('makeCensusCache: the first read never blocks — it reports pending, then fills', async () => {
  let calls = 0;
  const cache = makeCensusCache({ run: async () => { calls += 1; return CSV; } });
  const first = cache.get(1000);
  assert.strictEqual(first.status, 'pending', 'a 15 s poll must never wait on a subprocess');
  await cache.settled();
  const second = cache.get(2000);
  assert.strictEqual(second.status, 'ok');
  assert.strictEqual(calls, 1);
  const names = second.items.map((i) => i.name);
  assert.ok(names.includes('wezbridge-fleet-board'));
  // The class that motivated the panel: exit 1 with nobody watching.
  assert.deepStrictEqual(second.silent.map((i) => i.name), ['routine-test-strength-wezbridge']);
  // ...and the contract exit that must NOT be painted as a failure.
  const gate = second.items.find((i) => i.name === 'wezbridge-steward-gate');
  assert.strictEqual(gate.class, 'contract-signal');
});

test('makeCensusCache: a failing schtasks reports the error, keeps serving', async () => {
  const cache = makeCensusCache({ run: async () => { throw new Error('schtasks exited 1'); } });
  cache.get(1000);
  await cache.settled();
  const v = cache.get(2000);
  assert.strictEqual(v.status, 'error');
  assert.match(v.error, /schtasks exited 1/);
  assert.deepStrictEqual(v.items, []);
});

test('makeCensusCache: inside the TTL it does not re-run the subprocess', async () => {
  let calls = 0;
  const cache = makeCensusCache({ ttlMs: 60000, run: async () => { calls += 1; return CSV; } });
  cache.get(1000);
  await cache.settled();
  cache.get(2000);
  cache.get(3000);
  await cache.settled();
  assert.strictEqual(calls, 1);
});

// ── the whole block ─────────────────────────────────────────────────────────

test('buildObservability: one dead source does not blank the other five', async () => {
  const intel = tmpIntel('all');
  // Queues and rollup are healthy; actions.jsonl and turns/ are absent.
  write(path.join(intel, 'queues', 'infra.jsonl'), jsonl([{ id: 'b', time: '2026-08-22T16:00:00.000Z', ok: false }]));
  write(path.join(intel, 'rollups', '2026-08-22.md'), '# Rollup\n');
  const cache = makeCensusCache({ run: async () => CSV });

  const out = buildObservability(intel, {
    now: Date.parse('2026-08-22T18:00:00.000Z'),
    censusCache: cache,
    hermesDir: path.join(intel, 'no-hermes-here'),
  });

  assert.strictEqual(out.queues.projects.length, 1, 'healthy source still works');
  assert.match(out.rollup.text, /Rollup/);
  assert.ok(out.actions.error, 'the broken source owns its own error');
  assert.ok(out.hermes_cron.error, 'and so does hermes');
  assert.strictEqual(out.waker.total, 0);

  for (const key of ['briefs', 'hermes_cron', 'queues', 'actions', 'rollup', 'waker']) {
    assert.ok(out[key].generated_at, `${key} must declare its own generated_at`);
  }
  assert.ok(out.generated_at);
});

test('buildObservability: with no census cache the panel says disabled, never fake-green', () => {
  const out = buildObservability(tmpIntel('nocensus'), { now: Date.now() });
  assert.strictEqual(out.census.status, 'disabled');
  assert.deepStrictEqual(out.census.items, []);
});
