#!/usr/bin/env node
'use strict';
/**
 * fleet-board.cjs — renders _intel/board.html: the operator's window on the fleet.
 *
 * WHY THIS EXISTS. On 2026-08-14 the operator asked "where will I see the tasks,
 * the pending decisions?" and the honest answer was: nowhere, you ask me. That
 * is the actual reason no plan of ours ever reaches "validated, done" — the exit
 * criterion has always been MY REPORT, and a report is exactly the thing that
 * can be narrated. He cannot tell working from churning, so he can never call it.
 *
 * WHY IT IS NOT A DASHBOARD SERVER. This repo has killed a browser dashboard
 * once and six always-on coordinators. The lesson kept from all of them is that
 * a component which must be ALIVE for you to see anything is a component whose
 * death is invisible. So:
 *
 *   - No server, no port, no daemon, no framework, no dependency.
 *   - No state of its own. Every number is derived from files that already exist.
 *   - It is REGENERATED by the 09:05 gate, which is a Task Scheduler job with no
 *     model in it. If that chain dies, this file simply stops changing.
 *   - THEREFORE IT MUST DECLARE ITS OWN AGE. A stale board showing confident
 *     numbers is the defect this fleet keeps re-finding: a view narrower than
 *     its subject reporting CLEAN instead of "I cannot see". The page carries
 *     its generation time and shouts when it is older than a day.
 *
 * If this script breaks, nothing stops. That is the whole point of it being a
 * renderer rather than a system.
 *
 *   node scripts/fleet-board.cjs            # write _intel/board.html
 *   node scripts/fleet-board.cjs --open     # ...and open it
 */
const fs = require('node:fs');
const path = require('node:path');
const { execFile } = require('node:child_process');
const { audit, loadTasks } = require('./fleet-steward.cjs');
const { evaluate } = require('./steward-gate.cjs');

const INTEL = process.env.WEZBRIDGE_INTEL_DIR || path.join(__dirname, '..', '..', '_intel');
const OUT = path.join(INTEL, 'board.html');
const OPEN_STATES = ['ready', 'queued', 'running', 'review', 'blocked', 'failed'];

// ---------------------------------------------------------------------------
// read
// ---------------------------------------------------------------------------

/**
 * The operator gate lives in EITHER place. T-0072 carries a top-level `gate`
 * with `contract: null`; newer tasks carry `contract.gate`. Reading only one
 * silently under-reports the questions he owes answers to, which is the single
 * thing this page exists to show.
 */
const gateOf = (t) => (t.contract && t.contract.gate) || t.gate || null;
const isOpen = (t) => OPEN_STATES.includes(t.state);

function readRulings() {
  try {
    return fs.readFileSync(path.join(INTEL, 'rulings.jsonl'), 'utf8')
      .split('\n').filter(Boolean)
      .map((l) => { try { return JSON.parse(l); } catch { return null; } })
      .filter(Boolean);
  } catch { return []; }
}

/** Last known run of a scheduled chain link, from the file it leaves behind. */
function lastRun(file) {
  const full = path.join(INTEL, file);
  try {
    const st = fs.statSync(full);
    return { at: st.mtimeMs, text: fs.readFileSync(full, 'utf8').trim().split('\n')[0] };
  } catch { return null; }
}

function routineRuns(dir = path.join(INTEL, 'routine-findings')) {
  let files;
  try { files = fs.readdirSync(dir); } catch { return []; }
  const out = [];
  for (const f of files) {
    if (!f.startsWith('run-') || !f.endsWith('.json')) continue;
    try {
      const rec = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
      const at = fs.statSync(path.join(dir, f)).mtimeMs;
      let verdict = 'no artifact';
      // Resolve relative to the routine-findings dir, as routine-audit.cjs
      // loadRuns() does. Reading it verbatim resolved against process cwd and
      // rendered a permanent false 'no artifact' on healthy routines — the bug
      // board-app inherited by porting this line (fixed there in 7729310).
      try {
        const ref = rec.findings_file || '';
        const target = path.isAbsolute(ref) ? ref : path.join(dir, ref);
        verdict = JSON.parse(fs.readFileSync(target, 'utf8')).verdict || '?';
      } catch { /* absent */ }
      out.push({ ...rec, at, verdict });
    } catch { /* skip */ }
  }
  return out.sort((a, b) => b.at - a.at);
}

// ---------------------------------------------------------------------------
// render helpers
// ---------------------------------------------------------------------------

const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const ageH = (ms, now) => Math.round((now - ms) / 3600000);

function ageText(h) {
  if (h < 1) return 'just now';
  if (h < 48) return `${h}h ago`;
  return `${Math.round(h / 24)}d ago`;
}

/** Long operator blockers are the QUESTION. Truncating them hides the ask. */
function blockerHtml(t) {
  const raw = t.blocker || (t.contract && t.contract._note) || t.next_action || '';
  if (!raw) return '<em class="dim">no question recorded — that is itself a problem</em>';
  return esc(raw).replace(/\n/g, '<br>');
}

// ---------------------------------------------------------------------------
// build
// ---------------------------------------------------------------------------

function build(now = Date.now()) {
  const tasks = loadTasks();
  const rulings = readRulings();
  const report = audit(tasks, now, INTEL);
  const { unruled } = evaluate({ findings: report.findings, rulings, now });

  const open = tasks.filter(isOpen);
  const waiting = open.filter((t) => gateOf(t) === 'operator')
    .sort((a, b) => new Date(a.updated_at || 0) - new Date(b.updated_at || 0));
  const inFlight = open.filter((t) => ['running', 'review'].includes(t.state));
  const rest = open.filter((t) => gateOf(t) !== 'operator' && !['running', 'review'].includes(t.state));

  const byRepo = {};
  for (const t of rest) (byRepo[t.repo] = byRepo[t.repo] || []).push(t);

  const gate = lastRun('steward-gate-latest.txt') || lastRun('steward-gate.log');
  const routines = routineRuns();

  // --- sections ------------------------------------------------------------

  const waitingRows = waiting.length ? waiting.map((t) => `
    <details class="q">
      <summary><b>${esc(t.id)}</b> <span class="repo">${esc(t.repo)}</span>
        ${esc(t.title)}
        <span class="age">${ageText(ageH(new Date(t.updated_at || t.created_at || 0).getTime(), now))}</span>
      </summary>
      <div class="qbody">${blockerHtml(t)}</div>
    </details>`).join('')
    : '<p class="empty">Nothing is waiting on you. This is a real claim: it means zero open tasks carry an operator gate.</p>';

  const unruledRows = unruled.length ? `<table><thead><tr>
      <th>id</th><th>repo</th><th>why it is on this list</th><th>age</th></tr></thead><tbody>
      ${unruled.map((f) => `<tr><td class="mono">${esc(f.id)}</td><td>${esc(f.repo)}</td>
        <td>${esc(f.category)} — ${esc(f.why || '')}</td><td class="mono">${f.age_hours}h</td></tr>`).join('')}
      </tbody></table>
      <p class="dim">These are past their deadline with no ruling from me. The gate exits 1 every day until each one is dispatched, cancelled, deferred with a date, or handed to you.</p>`
    : '<p class="empty ok">Nothing unruled past deadline — the gate is green.</p>';

  const flightRows = inFlight.length ? `<table><thead><tr>
      <th>id</th><th>repo</th><th>state</th><th>owner</th><th>title</th><th>quiet for</th></tr></thead><tbody>
      ${inFlight.map((t) => `<tr><td class="mono">${esc(t.id)}</td><td>${esc(t.repo)}</td>
        <td><span class="pill s-${esc(t.state)}">${esc(t.state)}</span></td>
        <td>${esc((t.lease && t.lease.owner) || '—')}</td><td>${esc(t.title)}</td>
        <td class="mono">${ageText(ageH(new Date(t.updated_at || 0).getTime(), now))}</td></tr>`).join('')}
      </tbody></table>`
    : '<p class="empty">Nothing is being worked on right now.</p>';

  const routineRows = routines.length ? `<table><thead><tr>
      <th>routine</th><th>repo</th><th>last run</th><th>runner</th><th>verdict</th><th>next due</th></tr></thead><tbody>
      ${routines.slice(0, 12).map((r) => {
    const cadence = Number(r.cadence_hours) > 0 ? Number(r.cadence_hours) : 168;
    const due = r.at + cadence * 3600000;
    const overdue = now > due + 24 * 3600000;
    return `<tr><td>${esc(r.routine)}</td><td>${esc(r.repo)}</td>
        <td class="mono">${ageText(ageH(r.at, now))}</td>
        <td class="mono ${r.exit_status === 0 ? 'good' : 'bad'}">exit ${esc(r.exit_status)}</td>
        <td class="${r.verdict === 'clean' ? 'good' : 'bad'}">${esc(r.verdict)}</td>
        <td class="mono ${overdue ? 'bad' : 'dim'}">${overdue ? 'OVERDUE' : new Date(due).toISOString().slice(0, 10)}</td></tr>`;
  }).join('')}</tbody></table>`
    : `<p class="empty">No routine has run yet. The first is scheduled for Sunday 04:00.
       Until one runs, silence detection stays disarmed on purpose — it cannot measure a schedule that has not fired.</p>`;

  const repoRows = Object.entries(byRepo)
    .sort((a, b) => b[1].length - a[1].length)
    .map(([repo, ts]) => `
      <details class="repo-group">
        <summary><b>${esc(repo)}</b> <span class="count">${ts.length}</span>
          ${[...new Set(ts.map((t) => t.state))].map((s) => `<span class="pill s-${esc(s)}">${esc(s)}</span>`).join('')}
        </summary>
        <table><tbody>${ts.map((t) => `<tr><td class="mono">${esc(t.id)}</td>
          <td><span class="pill s-${esc(t.state)}">${esc(t.state)}</span></td>
          <td>${esc(t.title)}</td>
          <td class="mono dim">${ageText(ageH(new Date(t.updated_at || t.created_at || 0).getTime(), now))}</td>
          </tr>`).join('')}</tbody></table>
      </details>`).join('');

  const gateGreen = unruled.length === 0;

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Fleet board</title>
<style>
:root{--bg:#0e1116;--panel:#161b22;--panel2:#1c2330;--ink:#e6edf3;--dim:#8b949e;--line:#2b3440;
 --ok:#3fb950;--bad:#f85149;--warn:#d29922;--accent:#58a6ff;--mono:Consolas,'Cascadia Code',monospace}
@media(prefers-color-scheme:light){:root{--bg:#f6f8fa;--panel:#fff;--panel2:#f0f3f6;--ink:#1f2328;
 --dim:#59636e;--line:#d1d9e0;--ok:#1a7f37;--bad:#cf222e;--warn:#9a6700;--accent:#0969da}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.6 -apple-system,'Segoe UI',Roboto,sans-serif}
.wrap{max-width:1100px;margin:0 auto;padding:32px 20px 80px}
h1{font-size:1.7rem;margin:0 0 4px} h2{font-size:1.1rem;margin:38px 0 10px;
 padding-bottom:7px;border-bottom:1px solid var(--line);display:flex;gap:10px;align-items:baseline}
h2 .n{font-family:var(--mono);font-size:.85rem;color:var(--dim)}
.mono{font-family:var(--mono);font-size:.86em} .dim{color:var(--dim)}
.good{color:var(--ok)} .bad{color:var(--bad)}
#stale{display:none;background:var(--bad);color:#fff;padding:12px 18px;border-radius:8px;
 margin:0 0 20px;font-weight:600}
.status{display:flex;flex-wrap:wrap;gap:10px;margin:16px 0 8px}
.stat{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:12px 16px;min-width:120px}
.stat b{display:block;font-size:1.5rem;line-height:1.2} .stat span{color:var(--dim);font-size:.78rem;
 text-transform:uppercase;letter-spacing:.05em}
.stat.red b{color:var(--bad)} .stat.green b{color:var(--ok)} .stat.amber b{color:var(--warn)}
table{width:100%;border-collapse:collapse;margin:8px 0;font-size:.9rem;display:block;overflow-x:auto}
@media(min-width:700px){table{display:table}}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--dim);font-size:.74rem;text-transform:uppercase;letter-spacing:.05em}
details{background:var(--panel);border:1px solid var(--line);border-radius:8px;margin:6px 0}
summary{padding:11px 16px;cursor:pointer;display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}
summary::-webkit-details-marker{color:var(--dim)}
.q summary b{font-family:var(--mono);font-size:.85rem;color:var(--accent)}
.qbody{padding:0 16px 16px;border-top:1px solid var(--line);margin-top:2px;padding-top:14px;
 font-size:.92rem;color:var(--ink)}
.repo{font-family:var(--mono);font-size:.76rem;color:var(--dim);background:var(--panel2);
 padding:1px 7px;border-radius:10px;border:1px solid var(--line)}
.age{margin-left:auto;font-family:var(--mono);font-size:.78rem;color:var(--dim)}
.count{font-family:var(--mono);font-size:.8rem;color:var(--dim)}
.pill{font-family:var(--mono);font-size:.7rem;padding:1px 7px;border-radius:10px;border:1px solid var(--line);color:var(--dim)}
.s-blocked{color:var(--bad);border-color:var(--bad)} .s-review{color:var(--warn);border-color:var(--warn)}
.s-running{color:var(--accent);border-color:var(--accent)}
.empty{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:14px 18px;color:var(--dim)}
.empty.ok{border-left:3px solid var(--ok)}
footer{margin-top:56px;padding-top:18px;border-top:1px solid var(--line);color:var(--dim);font-size:.83rem}
</style></head><body><div class="wrap">

<div id="stale"></div>

<h1>Fleet board</h1>
<p class="dim mono" id="gen">generated ${new Date(now).toISOString()}</p>

<div class="status">
  <div class="stat ${waiting.length ? 'amber' : 'green'}"><b>${waiting.length}</b><span>waiting on you</span></div>
  <div class="stat ${gateGreen ? 'green' : 'red'}"><b>${unruled.length}</b><span>waiting on me</span></div>
  <div class="stat"><b>${open.length}</b><span>open tasks</span></div>
  <div class="stat"><b>${inFlight.length}</b><span>in flight</span></div>
  <div class="stat ${gateGreen ? 'green' : 'red'}"><b>${gateGreen ? 'GREEN' : 'RED'}</b><span>gate</span></div>
</div>
<p class="dim">Last gate run: ${gate ? `${ageText(ageH(gate.at, now))} — ${esc(gate.text).slice(0, 90)}` : '<span class="bad">never / not found</span>'}</p>

<h2>Decisions waiting on you <span class="n">${waiting.length}</span></h2>
${waitingRows}

<h2>Waiting on me <span class="n">${unruled.length}</span></h2>
${unruledRows}

<h2>In flight <span class="n">${inFlight.length}</span></h2>
${flightRows}

<h2>Routines <span class="n">${routines.length} run${routines.length === 1 ? '' : 's'} recorded</span></h2>
${routineRows}

<h2>Open work by project <span class="n">${rest.length} across ${Object.keys(byRepo).length}</span></h2>
${repoRows || '<p class="empty">No other open work.</p>'}

<footer>
Static file. No server, no port, nothing running. Regenerated by the 09:05 steward gate, a Task Scheduler
job with no model in it — so if the chain dies this page simply stops changing, and the banner above says so.
Every number is derived from <code>_intel/tasks/*.json</code>, <code>_intel/rulings.jsonl</code> and
<code>_intel/routine-findings/</code>. Regenerate any time with <code>node wezbridge/scripts/fleet-board.cjs</code>.
</footer>
</div>
<script>
// The board must not present confident numbers it can no longer vouch for.
// Generated server-side, aged client-side, because a static file cannot know
// when you are reading it.
(function(){
  var gen = new Date(${JSON.stringify(new Date(now).toISOString())});
  var hours = (Date.now() - gen.getTime()) / 3600000;
  document.getElementById('gen').textContent =
    'generated ' + gen.toLocaleString() + ' \\u00b7 ' +
    (hours < 1 ? 'moments ago' : Math.round(hours) + 'h ago');
  if (hours > 26) {
    var el = document.getElementById('stale');
    el.style.display = 'block';
    el.textContent = 'STALE: this board is ' + Math.round(hours/24) + ' day(s) old. ' +
      'The 09:05 job has not regenerated it, so every number below is from ' +
      gen.toLocaleDateString() + '. Do not trust them.';
  }
})();
</script>
</body></html>`;
}

if (require.main === module) {
  fs.writeFileSync(OUT, build());
  console.log(`fleet-board: wrote ${OUT}`);
  if (process.argv.includes('--open')) {
    execFile('cmd', ['/c', 'start', '', OUT], () => {});
  }
}

module.exports = { build, gateOf, routineRuns, OUT };
