@echo off
REM install-autostart.cmd
REM Drops a Windows-Startup-folder shortcut so the wezbridge dashboard
REM daemon (which arms the session-snapshot watcher) auto-starts on user
REM login. Idempotent — re-running replaces the existing shortcut.
REM
REM No admin required. Removes any prior shortcut by the same name.
REM
REM To uninstall: delete %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\wezbridge-dashboard.cmd

setlocal

set "WEZBRIDGE_DIR=%~dp0.."
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "TARGET=%STARTUP%\wezbridge-dashboard.cmd"

if not exist "%STARTUP%" (
    echo [install-autostart] ERROR: Startup folder not found at %STARTUP%
    exit /b 1
)

REM Build a small launcher script in Startup. Uses absolute paths so it
REM doesn't depend on PWD or PATH.
> "%TARGET%" echo @echo off
>> "%TARGET%" echo REM Auto-generated by wezbridge scripts/install-autostart.cmd
>> "%TARGET%" echo REM Launches the wezbridge dashboard daemon at user login.
>> "%TARGET%" echo cd /d "%WEZBRIDGE_DIR%"
>> "%TARGET%" echo start /B "" node src\dashboard-server.cjs ^>^> logs\dashboard.log 2^>^&1

echo [install-autostart] Installed: %TARGET%
echo.
echo The wezbridge dashboard daemon will now start automatically at user
echo login. The session-snapshot watcher arms by default (v3.4.1+),
echo capturing every claude.exe/codex.exe pane's launch state.
echo.
echo To uninstall: del "%TARGET%"
echo To opt OUT of session snapshots: set WEZBRIDGE_SESSION_SNAPSHOT=0 in your environment

endlocal
exit /b 0
